# Generated by Django 5.2.7 on 2025-10-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Телефон')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='ФИО')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('total_orders', models.IntegerField(default=0, verbose_name='Всего заказов')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Всего потрачено')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='Имя сотрудника')),
                ('surname', models.CharField(max_length=40, verbose_name='Фамилия сотрудника')),
                ('position', models.CharField(max_length=30, verbose_name='Должность')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Зарплата')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=50, verbose_name='Mail')),
                ('hire_date', models.DateField(verbose_name='Дата приема')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=100, verbose_name='Название блюда')),
                ('category', models.CharField(max_length=20, verbose_name='Категория')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cooking_time', models.IntegerField(default=15, verbose_name='Время приготовления (мин)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно')),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True, verbose_name='Номер столика')),
                ('capacity', models.IntegerField(verbose_name='Вместимость')),
                ('status', models.CharField(default='free', max_length=15, verbose_name='Статус')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Расположение')),
            ],
        ),
    ]
