# Generated by Django 5.2.7 on 2025-10-08 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(verbose_name='Дата заказа')),
                ('status', models.CharField(choices=[('pending', 'Принят'), ('preparing', 'Готовится'), ('ready', 'Готов'), ('served', 'Подано'), ('paid', 'Оплачен'), ('cancelled', 'Отменен')], default='pending', max_length=15, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая сумма')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='d_app.costomers', verbose_name='Клиент')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='d_app.employees', verbose_name='Сотрудник')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='d_app.tables', verbose_name='Столик')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за единицу')),
                ('special_requests', models.TextField(blank=True, verbose_name='Особые пожелания')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='d_app.menu', verbose_name='Блюдо')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='d_app.orders', verbose_name='Заказ')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('reservation_date', models.DateTimeField(verbose_name='Дата бронирования')),
                ('guests_count', models.IntegerField(verbose_name='Количество гостей')),
                ('status', models.CharField(choices=[('confirmed', 'Подтверждено'), ('pending', 'Ожидание'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=15, verbose_name='Статус')),
                ('duration', models.IntegerField(default=120, verbose_name='Продолжительность (мин)')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='d_app.tables', verbose_name='Столик')),
            ],
        ),
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField(verbose_name='Дата смены')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Отработано часов')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='d_app.employees', verbose_name='Сотрудник')),
            ],
        ),
    ]
